### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PenthouseLA** [tuxuser/ritto_doorbell#1]
Hey, ziehst du den Strom direkt vom 24V Pin oder seperat?

**Comment by tuxuser** [comment]
Hi, habe die README nochmal geupdated. Leider hat die Schaltung nie gut funktioniert, weder das Klingelsignal noch das Türöffnen.

Empfehlung: Lösung von GreatScott adaptieren.
-> https://www.youtube.com/watch?v=ZrkAWSemDC8

Um weitere Verwirrungen zu vermeiden wird das Repository nun archiviert - komplett löschen möchte ich es nämlich ungern.

PS: Hatte eine externe Stromversorgung genutzt.
